### ISSUE TITLE
Mac Port

### ISSUE THREAD

**Issue by SimonWaters** [surevine/Metre#7]
Noted that on the Mac, the Unicode headers are in a distinct folder, however the current build does not add the ICU_INCLUDE_DIR to the path for includes.

Not sure on the correct CMake approach for this is, but my hacky changes will make it "clearer" what is wrong, even if it isn't the correct fix.

<pre>
diff --git a/CMakeLists.txt b/CMakeLists.txt
index d3423e0..9649a0b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -37,11 +37,11 @@ message("ICU dir is ${ICU_INCLUDE_DIR}")
 set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wall -pedantic -O0 -g -DSIGSLOT_PURE_ISO")
 set(ICU_LIBS)
 if (ICU2_INCLUDE_DIR)
-    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DHAVE_ICU2")
+    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -L/usr/local/Cellar/icu4c/58.2/lib/ -I ${ICU2_INCLUDE_DIR} -DHAVE_ICU2")
     message("Found ICU2")
     set(ICU_LIBS icudata icuuc)
 elseif (ICU_INCLUDE_DIR)
-    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DHAVE_ICU")
+    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -I ${ICU_INCLUDE_DIR} -DHAVE_ICU")
     message("Found ICU")
     set(ICU_LIBS icudata icuuc)
</pre>

**Comment by dwd** [comment]
We have working Mac OS X builds.
